import {
  CalendarEvent,
  ChannelConnectorStatus,
  ContentItem,
  Conversation,
  MediaAsset,
  PostPerformance,
  Project,
  User,
} from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-ceilings",
    name: "ФЕНИКС PRO Потолки",
    slug: "ceilings",
    niche_type: "ceilings",
    description: "Натяжные потолки в Улан-Удэ и районах. Теневые, парящие, световые линии, треки.",
    knowledge_dir: "/app/knowledge/ceilings",
    system_prompt:
      "Ты AI-помощник менеджера компании ФЕНИКС PRO по натяжным потолкам. Пиши краткий, вежливый черновик ответа клиенту. Мягко веди к бесплатному замеру.",
    is_active: true,
    color: "#0f766e", // teal-700
    created_at: "2026-08-01T10:00:00Z",
  },
  {
    id: "proj-kitchens",
    name: "ФЕНИКС Кухни & Корпус",
    slug: "kitchens",
    niche_type: "kitchens",
    description: "Кухонные гарнитуры и корпусная мебель на заказ под ключ с 3D-проектом.",
    knowledge_dir: "/app/knowledge/kitchens",
    system_prompt:
      "Ты AI-помощник компании ФЕНИКС Кухни. Консультируй по материалам фасадов (МДФ, эмаль, пластик), столешницам и фурнитуре. Предлагай бесплатный 3D-проект.",
    is_active: true,
    color: "#c2410c", // orange-700
    created_at: "2026-08-15T12:00:00Z",
  },
  {
    id: "proj-windows",
    name: "ФЕНИКС Окна & Балконы",
    slug: "windows",
    niche_type: "windows",
    description: "Пластиковые окна VEKA/Rehau, остекление и утепление лоджий.",
    knowledge_dir: "/app/knowledge/windows",
    system_prompt:
      "Ты AI-помощник компании ФЕНИКС Окна. Уточняй серию профиля, размеры проема, тип стеклопакета и приглашай инженера на замер.",
    is_active: true,
    color: "#2563eb", // blue-600
    created_at: "2026-08-20T09:00:00Z",
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    project_id: "proj-ceilings",
    channel: "vk",
    contact_id: "c-1",
    contact: {
      id: "c-1",
      name: "Алексей Смирнов",
      phone: "+7 (902) 512-34-56",
      primary_channel: "vk",
      city: "Улан-Удэ, Октябрьский р-н",
      notes: "Новостройка в ЖК Любимый, ремонт в разгаре",
    },
    external_chat_id: "vk-peer-205843263_4921",
    status: "open",
    last_text: "А если еще скрытый карниз с подсветкой добавить, сколько примерно выйдет?",
    last_message_at: "2026-09-08T09:58:00Z",
    unread_count: 2,
    messages: [
      {
        id: "m-1",
        conversation_id: "conv-1",
        direction: "inbound",
        sender_type: "client",
        text: "Здравствуйте! Хотим натяжной потолок в гостиную 18 м2. Интересует теневой профиль и 6 спотов.",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T09:40:00Z",
        created_at: "2026-09-08T09:35:00Z",
      },
      {
        id: "m-2",
        conversation_id: "conv-1",
        direction: "outbound",
        sender_type: "operator",
        text: "Здравствуйте, Алексей! С теневым профилем EuroKRAAB и спотами получается очень стильный минимализм. Предварительно по этим параметрам ориентир около 28 000 - 34 000 руб. под ключ с полотном и монтажом.",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T09:42:00Z",
        created_at: "2026-09-08T09:41:00Z",
      },
      {
        id: "m-3",
        conversation_id: "conv-1",
        direction: "inbound",
        sender_type: "client",
        text: "А если еще скрытый карниз с подсветкой добавить, сколько примерно выйдет?",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T10:05:00Z",
        created_at: "2026-09-08T09:58:00Z",
      },
      {
        id: "m-4",
        conversation_id: "conv-1",
        direction: "inbound",
        sender_type: "client",
        text: null,
        media_type: "photo",
        media_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80",
        caption: "Вот фото зала, потолок монолитный. Стены уже оштукатурены.",
        file_id: "vk_photo_984321",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T10:06:00Z",
        created_at: "2026-09-08T10:05:00Z",
      },
      {
        id: "m-5",
        conversation_id: "conv-1",
        direction: "inbound",
        sender_type: "client",
        text: null,
        media_type: "voice",
        duration_sec: 24,
        file_id: "vk_voice_102934",
        delivery_status: "delivered",
        is_read: false,
        read_at: null,
        created_at: "2026-09-08T10:10:00Z",
      },
      {
        id: "m-6",
        conversation_id: "conv-1",
        direction: "inbound",
        sender_type: "client",
        text: null,
        media_type: "document",
        file_name: "План_квартиры_ЖК_Любимый.pdf",
        file_size: 1945600,
        caption: "Прикрепил план БТИ с размерами комнат для точного расчета.",
        file_id: "vk_doc_77123",
        delivery_status: "delivered",
        is_read: false,
        read_at: null,
        created_at: "2026-09-08T10:12:00Z",
      },
    ],
    lead: {
      id: "lead-1",
      project_id: "proj-ceilings",
      contact_id: "c-1",
      conversation_id: "conv-1",
      source: "vk",
      status: "qualifying",
      temperature: "hot",
      area_m2: 18,
      rooms_count: 1,
      lights_count: 6,
      cornice: true,
      ceiling_type: "теневой",
      address: "ул. Бабушкина, 42",
      desired_date: "12-14 сентября",
      phone_received: true,
      measurement_planned: false,
      estimated_price: 36500,
      updated_at: "2026-09-08T09:58:00Z",
    },
    calculation: {
      id: "calc-1",
      lead_id: "lead-1",
      conversation_id: "conv-1",
      area_m2: 18,
      perimeter_m: 17.5,
      profile_type: "shadow",
      profile_subtype: "plastic",
      angles_count: 4,
      cornices: {
        cornice_1: { type: "hidden", length: 3.2, led: true },
      },
      lights: {
        spot: 6,
        chandelier: 0,
        light_line: 0,
      },
      vent_points: 0,
      smart_setup: false,
      discount_category: "novosel",
      estimate_min: 34500,
      estimate_max: 39800,
      breakdown: [
        { category: "fabric", label: "Полотно матовое премиум MSD", unit: "м2", quantity: 18, min_total: 14400, max_total: 16200 },
        { category: "profile", label: "Теневой профиль EuroKRAAB", unit: "пог.м", quantity: 17.5, min_total: 14000, max_total: 16500 },
        { category: "lights", label: "Монтаж накладных спотов", unit: "шт", quantity: 6, min_total: 3300, max_total: 3900 },
        { category: "cornice", label: "Скрытый карниз ПК-5 (3.2 м) + LED", unit: "пог.м", quantity: 3.2, min_total: 5800, max_total: 7200 },
        { category: "discount", label: "Скидка новосела (-10%)", unit: "%", quantity: 10, min_total: -3000, max_total: -4000 },
      ],
    },
    pending_suggestion: {
      id: "sug-1",
      suggested_text:
        "Скрытая ниша под карниз с LED-подсветкой добавит ориентировочно 5 500 - 7 000 руб. в зависимости от длины (обычно 3-3.5 м). Точную сумму мастер посчитает прямо на замере с образцами лент и профилей. Подскажите, в какой день вам удобнее принять замерщика — сегодня вечером или завтра?",
      confidence: 0.88,
      mode: "draft",
      status: "pending",
      rag_sources: ["pricing.md", "calculator.md"],
      created_at: "2026-09-08T09:58:30Z",
    },
  },
  {
    id: "conv-2",
    project_id: "proj-ceilings",
    channel: "telegram",
    contact_id: "c-2",
    contact: {
      id: "c-2",
      name: "Екатерина В.",
      phone: "+7 (914) 830-11-22",
      primary_channel: "telegram",
      city: "Улан-Удэ",
      notes: "Пришла из Telegram-канала по промокоду ЗАМЕР",
    },
    external_chat_id: "tg-chat-78192314",
    status: "open",
    last_text: "ЗАМЕР, здравствуйте! Хотим узнать по стоимости на всю квартиру 54 м2.",
    last_message_at: "2026-09-08T09:12:00Z",
    unread_count: 1,
    messages: [
      {
        id: "m-201",
        conversation_id: "conv-2",
        direction: "inbound",
        sender_type: "client",
        text: "ЗАМЕР, здравствуйте! Хотим узнать по стоимости на всю квартиру 54 м2.",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T09:15:00Z",
        created_at: "2026-09-08T09:12:00Z",
      },
      {
        id: "m-202",
        conversation_id: "conv-2",
        direction: "inbound",
        sender_type: "client",
        text: null,
        media_type: "photo",
        media_url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=900&auto=format&fit=crop&q=80",
        caption: "Вот фото коридора и кухни. Хотим бесщелевое примыкание без пластиковых заглушек.",
        file_id: "tg_photo_109283",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T09:16:00Z",
        created_at: "2026-09-08T09:15:30Z",
      },
      {
        id: "m-203",
        conversation_id: "conv-2",
        direction: "inbound",
        sender_type: "client",
        text: null,
        media_type: "voice",
        duration_sec: 18,
        file_id: "tg_voice_88412",
        delivery_status: "delivered",
        is_read: false,
        read_at: null,
        created_at: "2026-09-08T09:18:00Z",
      },
    ],
    lead: {
      id: "lead-2",
      project_id: "proj-ceilings",
      contact_id: "c-2",
      conversation_id: "conv-2",
      source: "telegram",
      status: "new",
      temperature: "hot",
      area_m2: 54,
      rooms_count: 3,
      lights_count: null,
      cornice: null,
      address: "105 квартал",
      desired_date: "как можно быстрее",
      phone_received: true,
      measurement_planned: false,
      estimated_price: 52000,
      updated_at: "2026-09-08T09:12:00Z",
    },
    calculation: {
      id: "calc-2",
      lead_id: "lead-2",
      conversation_id: "conv-2",
      area_m2: 54,
      perimeter_m: 48,
      profile_type: "classic",
      estimate_min: 48000,
      estimate_max: 65000,
      breakdown: [
        { category: "fabric", label: "Полотно матовое на 3 комнаты", unit: "м2", quantity: 54, min_total: 35000, max_total: 44000 },
        { category: "profile", label: "Классический стеновой профиль", unit: "пог.м", quantity: 48, min_total: 13000, max_total: 21000 },
      ],
    },
    pending_suggestion: {
      id: "sug-2",
      suggested_text:
        "Здравствуйте, Екатерина! На 54 м² (3 комнаты) базовый белый матовый потолок под ключ ориентировочно выходит от 48 000 до 65 000 руб. Точная сумма зависит от количества светильников и карнизов. Мастер может бесплатно заехать сегодня с 16:00 до 19:00, замерить все помещения и показать образцы. Подойдет это время?",
      confidence: 0.92,
      mode: "draft",
      status: "pending",
      rag_sources: ["pricing.md", "company.md"],
      created_at: "2026-09-08T09:12:20Z",
    },
  },
  {
    id: "conv-3",
    project_id: "proj-ceilings",
    channel: "max",
    contact_id: "c-3",
    contact: {
      id: "c-3",
      name: "Дмитрий К.",
      phone: null,
      primary_channel: "max",
      city: "Улан-Удэ",
      notes: "Тестовый входящий диалог из соцсети Max",
    },
    external_chat_id: "max-user-99120",
    status: "open",
    last_text: "Добрый день! Подскажите, делаете ли парящие потолки с RGB подсветкой?",
    last_message_at: "2026-09-08T08:30:00Z",
    unread_count: 1,
    messages: [
      {
        id: "m-301",
        conversation_id: "conv-3",
        direction: "inbound",
        sender_type: "client",
        text: "Добрый день! Подскажите, делаете ли парящие потолки с RGB подсветкой?",
        delivery_status: "delivered",
        is_read: false,
        read_at: null,
        created_at: "2026-09-08T08:30:00Z",
      },
    ],
    lead: {
      id: "lead-3",
      project_id: "proj-ceilings",
      contact_id: "c-3",
      conversation_id: "conv-3",
      source: "max",
      status: "new",
      temperature: "warm",
      area_m2: null,
      rooms_count: 1,
      ceiling_type: "парящий RGB",
      phone_received: false,
      measurement_planned: false,
      updated_at: "2026-09-08T08:30:00Z",
    },
    pending_suggestion: {
      id: "sug-3",
      suggested_text:
        "Здравствуйте, Дмитрий! Да, делаем парящие потолки с качественной RGB-лентой и управлением со смартфона или пульта. Подскажите, пожалуйста, какая примерно площадь комнаты и планируется ли еще основной свет?",
      confidence: 0.85,
      mode: "draft",
      status: "pending",
      rag_sources: ["pricing.md", "faq.md"],
      created_at: "2026-09-08T08:30:25Z",
    },
  },
  {
    id: "conv-4",
    project_id: "proj-kitchens",
    channel: "vk",
    contact_id: "c-4",
    contact: {
      id: "c-4",
      name: "Ольга Николаева",
      phone: "+7 (908) 590-77-88",
      primary_channel: "vk",
      city: "Улан-Удэ, Энергетик",
      notes: "Кухня 3.2 метра, стиль Неоклассика",
    },
    external_chat_id: "vk-peer-205843263_8123",
    status: "open",
    last_text: "Здравствуйте! Хотим прямую кухню 3.2м, фасады эмаль матовая, фурнитура Blum. Сколько выйдет ориентир?",
    last_message_at: "2026-09-08T07:45:00Z",
    unread_count: 0,
    messages: [
      {
        id: "m-401",
        conversation_id: "conv-4",
        direction: "inbound",
        sender_type: "client",
        text: "Здравствуйте! Хотим прямую кухню 3.2м, фасады эмаль матовая, фурнитура Blum. Сколько выйдет ориентир?",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T07:50:00Z",
        created_at: "2026-09-08T07:45:00Z",
      },
      {
        id: "m-402",
        conversation_id: "conv-4",
        direction: "outbound",
        sender_type: "operator",
        text: "Ольга, добрый день! Прямая кухня 3.2 м в крашеной эмали с доводчиками Blum и влагостойкой столешницей 38 мм обычно выходит в диапазоне 175 000 - 220 000 руб. под ключ с доставкой и установкой.",
        delivery_status: "delivered",
        is_read: true,
        read_at: "2026-09-08T07:55:00Z",
        created_at: "2026-09-08T07:52:00Z",
      },
    ],
    lead: {
      id: "lead-4",
      project_id: "proj-kitchens",
      contact_id: "c-4",
      conversation_id: "conv-4",
      source: "vk",
      status: "qualifying",
      temperature: "warm",
      area_m2: null,
      address: "мкрн. Энергетик, д. 18",
      phone_received: true,
      measurement_planned: false,
      estimated_price: 195000,
      custom_fields: {
        kitchen_length_m: 3.2,
        facade_material: "эмаль матовая",
        hardware: "Blum",
        countertop: "пластик HPL влагостойкий",
      },
      updated_at: "2026-09-08T07:52:00Z",
    },
    pending_suggestion: {
      id: "sug-4",
      suggested_text:
        "Мы можем бесплатно составить 3D-проект под ваши размеры с точным расположением техники и мойки. Прислать примеры похожих реализованных кухонь?",
      confidence: 0.82,
      mode: "draft",
      status: "pending",
      rag_sources: ["pricing.md", "calculator.md"],
      created_at: "2026-09-08T07:52:30Z",
    },
  },
  {
    id: "conv-5",
    project_id: "proj-windows",
    channel: "avito",
    contact_id: "c-5",
    contact: {
      id: "c-5",
      name: "Баир Ц.",
      phone: "+7 (924) 450-99-00",
      primary_channel: "avito",
      city: "Улан-Удэ, п. Сотниково",
      notes: "Частный дом, нужно 7 окон",
    },
    external_chat_id: "avito-chat-3341",
    status: "open",
    last_text: "Нужно остеклить дом, 7 стандартных окон 1300х1400 с 5-камерным профилем. Есть скидки на объем?",
    last_message_at: "2026-09-08T06:10:00Z",
    unread_count: 1,
    messages: [
      {
        id: "m-501",
        conversation_id: "conv-5",
        direction: "inbound",
        sender_type: "client",
        text: "Нужно остеклить дом, 7 стандартных окон 1300х1400 с 5-камерным профилем. Есть скидки на объем?",
        delivery_status: "delivered",
        is_read: false,
        read_at: null,
        created_at: "2026-09-08T06:10:00Z",
      },
    ],
    lead: {
      id: "lead-5",
      project_id: "proj-windows",
      contact_id: "c-5",
      conversation_id: "conv-5",
      source: "avito",
      status: "new",
      temperature: "hot",
      address: "п. Сотниково",
      phone_received: true,
      measurement_planned: false,
      estimated_price: 135000,
      custom_fields: {
        windows_count: 7,
        profile_chamber: "5-камерный VEKA 70mm",
        double_glazing: "энергосберегающий 40мм",
      },
      updated_at: "2026-09-08T06:10:00Z",
    },
    pending_suggestion: {
      id: "sug-5",
      suggested_text:
        "Здравствуйте, Баир! Да, на 7 окон действует скидка за объем 12% плюс энергосберегающие стеклопакеты в подарок. На 7 окон 1300х1400 профиль 70 мм ориентир около 130 000 - 145 000 руб. под ключ с монтажом и подоконниками. В какой день инженеру удобно приехать в Сотниково на точный замер?",
      confidence: 0.91,
      mode: "draft",
      status: "pending",
      created_at: "2026-09-08T06:10:30Z",
    },
  },
];

export const INITIAL_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "cnt-1",
    project_id: "proj-ceilings",
    title: "Почему потолок 18 м2 у соседей стоит по-разному",
    topic: "Разбор ценообразования: профиль, углы, светильники, карниз и подготовка помещения.",
    rubric: "Цена и смета",
    goal: "lead_generation",
    offer: "рассчитаем точную вилку по вашему плану и зафиксируем цену на замере",
    trigger_keyword: "РАСЧЕТ",
    status: "approved",
    variants: [
      {
        id: "var-1",
        content_item_id: "cnt-1",
        channel: "vk_wall",
        title: "Почему потолок 18 м2 у соседей стоит по-разному?",
        text: `Почему потолок 18 м² у двух соседей в одном доме может стоить с разницей в 2 раза? 🤔\n\nЧасто спрашивают: «Сколько стоит квадратный метр?». Но итоговая смета натяжного потолка складывается не только из площади полотна:\n\n1. Тип примыкания: классическая вставка или современный теневой зазор EuroKRAAB без заглушек.\n2. Освещение: простая люстра или 8 аккуратных спотов с разделением зон.\n3. Карниз: накладной или скрытая ниша с эффектом «шторы парят из потолка».\n4. Количество углов и обход труб.\n\nМы всегда за честную смету без скрытых доплат. Напишите «РАСЧЕТ» в личные сообщения — прикинем смету по вашим размерам!`,
        format: "post",
        status: "approved",
        scheduled_at: "2026-09-09T09:00:00Z",
      },
      {
        id: "var-2",
        content_item_id: "cnt-1",
        channel: "telegram",
        title: "Почему квадратный метр — обманчивая цифра",
        text: `💡 Почему нельзя верить цене «от 350 руб./м²»?\n\nПотому что реальная смета — это не только полотно, а профиль, геометрия углов, скрытый карниз и правильная разводка света.\n\nВчера считали две одинаковые комнаты 18 м²:\n• В первой: классика с люстрой = 14 200 руб.\n• Во второй: теневой профиль + 6 спотов + скрытый карниз с подсветкой = 33 500 руб.\n\nНапишите в ЛС бота кодовое слово РАСЧЕТ — быстро сориентируем по вашим параметрам!`,
        format: "post",
        status: "scheduled",
        scheduled_at: "2026-09-10T08:00:00Z",
      },
      {
        id: "var-3",
        content_item_id: "cnt-1",
        channel: "max",
        title: "Коротко о цене потолка",
        text: `Потолок 18 м² может стоить и 14 000 руб., и 35 000 руб. Все решает профиль (классика или теневой) и освещение. Напишите РАСЧЕТ, и мы быстро сориентируем по вашей комнате!`,
        format: "post",
        status: "draft",
      },
    ],
    media_assets: [
      {
        id: "med-1",
        project_id: "proj-ceilings",
        content_item_id: "cnt-1",
        title: "Теневой потолок в гостиной с трековым светом",
        asset_type: "photo",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
        tags: ["гостиная", "теневой", "треки"],
        created_at: "2026-09-02T10:00:00Z",
      },
    ],
    created_at: "2026-09-01T12:00:00Z",
    updated_at: "2026-09-07T15:00:00Z",
  },
  {
    id: "cnt-2",
    project_id: "proj-ceilings",
    title: "Скрытый карниз с подсветкой: когда планировать",
    topic: "Как правильно спланировать нишу под шторы до чистовой отделки стен.",
    rubric: "Технологии и ремонт",
    goal: "trust",
    offer: "бесплатный выезд инженера для согласования ниш",
    trigger_keyword: "КАРНИЗ",
    status: "scheduled",
    variants: [
      {
        id: "var-4",
        content_item_id: "cnt-2",
        channel: "vk_wall",
        title: "Скрытый карниз для штор",
        text: `Скрытый карниз — деталь, которая делает ремонт в 2 раза визуально дороже. Шторы струятся прямо из потолка, а креплений и крючков не видно. Главное — заложить проводку и согласовать ширину ниши до натяжки полотна. Напишите «КАРНИЗ» для консультации!`,
        format: "post",
        status: "scheduled",
        scheduled_at: "2026-09-12T11:00:00Z",
      },
    ],
    media_assets: [],
    created_at: "2026-09-03T11:00:00Z",
    updated_at: "2026-09-06T10:00:00Z",
  },
  {
    id: "cnt-3",
    project_id: "proj-kitchens",
    title: "Топ-5 ошибок при заказе кухни в 2026 году",
    topic: "Розетки, открывание шкафов, высота столешницы, мойка и подсветка рабочей зоны.",
    rubric: "Полезно",
    goal: "lead_generation",
    offer: "составим 3D-проект кухни с правильной эргономикой",
    trigger_keyword: "ПРОЕКТ",
    status: "draft",
    variants: [
      {
        id: "var-5",
        content_item_id: "cnt-3",
        channel: "vk_wall",
        text: `5 ошибок при планировании кухни, о которых жалеют после ремонта: 1. Розетки не там, где приборы. 2. Мало рабочей зоны между мойкой и плитой. 3. Распашные нижние шкафы вместо выдвижных ящиков. 4. Нет подсветки фартука. 5. Заказ кухни вслепую без 3D-визуализации. Напишите ПРОЕКТ — нарисуем вашу идеальную кухню бесплатно!`,
        format: "post",
        status: "draft",
      },
    ],
    media_assets: [],
    created_at: "2026-09-05T09:00:00Z",
    updated_at: "2026-09-05T09:00:00Z",
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "ev-1",
    content_item_id: "cnt-1",
    content_variant_id: "var-1",
    content_title: "Почему потолок 18 м2 у соседей стоит по-разному",
    channel: "vk_wall",
    text: "Разбор ценообразования с фото объекта",
    scheduled_at: "2026-09-09T09:00:00Z",
    status: "scheduled",
  },
  {
    id: "ev-2",
    content_item_id: "cnt-1",
    content_variant_id: "var-2",
    content_title: "Почему квадратный метр — обманчивая цифра",
    channel: "telegram",
    text: "Пост для Telegram с разбором реального кейса",
    scheduled_at: "2026-09-10T08:00:00Z",
    status: "scheduled",
  },
  {
    id: "ev-3",
    content_item_id: "cnt-2",
    content_variant_id: "var-4",
    content_title: "Скрытый карниз для штор",
    channel: "vk_wall",
    text: "Скрытый карниз с подсветкой и инструкцией",
    scheduled_at: "2026-09-12T11:00:00Z",
    status: "scheduled",
  },
  {
    id: "ev-4",
    content_item_id: "cnt-1",
    content_variant_id: "var-3",
    content_title: "Коротко о цене потолка",
    channel: "max",
    text: "Короткий пост для канала Max",
    scheduled_at: "2026-09-14T15:00:00Z",
    status: "scheduled",
  },
];

export const INITIAL_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: "med-1",
    project_id: "proj-ceilings",
    content_item_id: "cnt-1",
    title: "Гостиная 18м² теневой EuroKRAAB",
    asset_type: "photo",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    description: "ЖК Любимый, белый матовый MSD Evolution, теневой зазор, 6 спотов",
    tags: ["потолки", "гостиная", "теневой"],
    created_at: "2026-09-02T10:00:00Z",
  },
  {
    id: "med-2",
    project_id: "proj-ceilings",
    content_item_id: null,
    title: "Парящий потолок с RGB лентой в спальне",
    asset_type: "photo",
    url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80",
    description: "Улан-Удэ, 105 квартал. Профиль LumFer, бегущий огонь",
    tags: ["потолки", "спальня", "rgb", "парящий"],
    created_at: "2026-09-04T14:30:00Z",
  },
  {
    id: "med-3",
    project_id: "proj-ceilings",
    content_item_id: "cnt-2",
    title: "Скрытый карниз ПК-5 у панорамного окна",
    asset_type: "photo",
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description: "Ниша 15 см, однорядная подсветка 4000K",
    tags: ["карниз", "подсветка", "окно"],
    created_at: "2026-09-05T12:00:00Z",
  },
  {
    id: "med-4",
    project_id: "proj-kitchens",
    content_item_id: "cnt-3",
    title: "Прямая кухня 3.2м графит и дерево",
    asset_type: "photo",
    url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80",
    description: "Фасады эмаль, столешница дуб Небраска, фурнитура Blum",
    tags: ["кухни", "графит", "blum"],
    created_at: "2026-09-06T16:00:00Z",
  },
];

export const INITIAL_CONNECTORS: ChannelConnectorStatus[] = [
  {
    channel: "vk",
    name: "ВКонтакте (Сообщения & Стена)",
    connected: true,
    polling_mode: "long_polling",
    is_active: true,
    last_heartbeat: "только что (Long Poll активен)",
    unread_events: 2,
    details: "Группа ID 205843263. Сообщения через сообщество + фото/стена подключены.",
  },
  {
    channel: "telegram",
    name: "Telegram (Бот Long Polling)",
    connected: true,
    polling_mode: "long_polling",
    is_active: true,
    last_heartbeat: "только что (getUpdates 25s)",
    unread_events: 1,
    details: "Бот с токеном 8809553443:... подключен (Long Polling getUpdates). Лиды и диалоги создаются автоматически.",
  },
  {
    channel: "max",
    name: "MAX (Коннектор-шаблон)",
    connected: false,
    polling_mode: "long_polling",
    is_active: false,
    last_heartbeat: "Ожидает настройки API методов",
    unread_events: 0,
    details: "Шаблон app.connectors.max создан. Готов к вставке API ключей и методов соцсети MAX.",
  },
  {
    channel: "avito",
    name: "Авито (Диалоги & Лиды)",
    connected: true,
    polling_mode: "manual",
    is_active: true,
    last_heartbeat: "5 мин. назад",
    unread_events: 1,
    details: "Профиль компании. Обработка входящих сообщений клиентов по объявлениям.",
  },
];

export const INITIAL_POST_PERFORMANCES: PostPerformance[] = [
  {
    id: "perf-1",
    project_id: "proj-ceilings",
    content_item_id: "cnt-1",
    content_title: "Почему потолок 18 м2 у соседей стоит по-разному",
    channel: "vk_wall",
    views_count: 4850,
    likes_count: 142,
    comments_count: 38,
    shares_count: 19,
    leads_count: 14,
    measurements_count: 6,
    conversion_rate: 9.86, // (14 / 142) * 100
    published_at: "2026-09-07T08:30:00Z",
    last_synced_at: "2026-09-08T11:30:00Z",
  },
  {
    id: "perf-2",
    project_id: "proj-ceilings",
    content_item_id: "cnt-1",
    content_title: "Почему потолок 18 м2 у соседей стоит по-разному (TG)",
    channel: "telegram",
    views_count: 2120,
    likes_count: 68,
    comments_count: 15,
    shares_count: 31,
    leads_count: 11,
    measurements_count: 4,
    conversion_rate: 16.18,
    published_at: "2026-09-07T08:35:00Z",
    last_synced_at: "2026-09-08T11:30:00Z",
  },
  {
    id: "perf-3",
    project_id: "proj-ceilings",
    content_item_id: "cnt-2",
    content_title: "Теневой зазор EuroKRAAB vs обычная заглушка: фотосравнение",
    channel: "vk_wall",
    views_count: 6140,
    likes_count: 230,
    comments_count: 49,
    shares_count: 45,
    leads_count: 21,
    measurements_count: 9,
    conversion_rate: 9.13,
    published_at: "2026-09-06T11:00:00Z",
    last_synced_at: "2026-09-08T11:30:00Z",
  },
  {
    id: "perf-4",
    project_id: "proj-ceilings",
    content_item_id: "cnt-2",
    content_title: "Теневой зазор EuroKRAAB vs обычная заглушка (TG)",
    channel: "telegram",
    views_count: 2890,
    likes_count: 114,
    comments_count: 27,
    shares_count: 52,
    leads_count: 17,
    measurements_count: 7,
    conversion_rate: 14.91,
    published_at: "2026-09-06T11:05:00Z",
    last_synced_at: "2026-09-08T11:30:00Z",
  },
  {
    id: "perf-5",
    project_id: "proj-kitchens",
    content_item_id: "cnt-3",
    content_title: "5 ошибок при заказе кухни, за которые переплачивают 60 000 ₽",
    channel: "vk_wall",
    views_count: 3400,
    likes_count: 185,
    comments_count: 34,
    shares_count: 28,
    leads_count: 16,
    measurements_count: 8,
    conversion_rate: 8.65,
    published_at: "2026-09-05T14:20:00Z",
    last_synced_at: "2026-09-08T11:30:00Z",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-owner",
    name: "Евгений Озари",
    email: "zhenayozari@gmail.com",
    role: "owner",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120",
  },
  {
    id: "usr-manager",
    name: "Анна Соколова (Менеджер)",
    email: "anna.manager@fenix-hub.ru",
    role: "manager",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120",
  },
];

